(function() {var implementors = {};
implementors["editeur"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='editeur/tuple/struct.Tuple.html' title='editeur::tuple::Tuple'>Tuple</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='enum' href='editeur/sheet/enum.Sheet.html' title='editeur::sheet::Sheet'>Sheet</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='enum' href='editeur/sprite/texel/part/enum.Part.html' title='editeur::sprite::texel::part::Part'>Part</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='editeur/sprite/texel/struct.Texel.html' title='editeur::sprite::texel::Texel'>Texel</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='editeur/sprite/draw/struct.Draw.html' title='editeur::sprite::draw::Draw'>Draw</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='editeur/sprite/struct.Sprite.html' title='editeur::sprite::Sprite'>Sprite</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='enum' href='editeur/emotion/enum.Emotion.html' title='editeur::emotion::Emotion'>Emotion</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='enum' href='editeur/position/enum.Posture.html' title='editeur::position::Posture'>Posture</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='editeur/struct.Graphic.html' title='editeur::Graphic'>Graphic</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
